import type { Config } from "tailwindcss";

// Design tokens reproduced from the client-supplied public UI reference
// (`tuition_serve_home (3).html`). Do not redesign these without an
// explicit change to the approved wireframe specification.
const config: Config = {
  content: ["./src/**/*.{ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "#bcc7de",
        "surface-container-high": "#e6e8ea",
        "inverse-primary": "#4edea3",
        "surface-bright": "#f7f9fb",
        "on-surface-variant": "#3c4a42",
        "on-secondary": "#ffffff",
        "tertiary-fixed-dim": "#adc6ff",
        "on-error-container": "#93000a",
        "surface-container-highest": "#e0e3e5",
        "on-secondary-fixed-variant": "#3c475a",
        primary: "#006c49",
        "surface-dim": "#d8dadc",
        "secondary-container": "#d5e0f8",
        "on-tertiary-fixed-variant": "#004395",
        "surface-container": "#eceef0",
        "tertiary-container": "#71a1ff",
        "on-tertiary-fixed": "#001a42",
        "on-tertiary-container": "#00367a",
        "on-primary": "#ffffff",
        error: "#ba1a1a",
        "primary-container": "#10b981",
        "surface-variant": "#e0e3e5",
        "error-container": "#ffdad6",
        "on-tertiary": "#ffffff",
        secondary: "#545f73",
        "on-error": "#ffffff",
        "on-surface": "#191c1e",
        "on-background": "#191c1e",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed": "#d8e3fb",
        "primary-fixed-dim": "#4edea3",
        "tertiary-fixed": "#d8e2ff",
        "on-secondary-container": "#586377",
        "outline-variant": "#bbcabf",
        "inverse-surface": "#2d3133",
        "on-primary-container": "#00422b",
        "surface-container-low": "#f2f4f6",
        tertiary: "#005ac2",
        background: "#f7f9fb",
        outline: "#6c7a71",
        surface: "#f7f9fb",
        "on-primary-fixed-variant": "#005236",
        "surface-tint": "#006c49",
        "inverse-on-surface": "#eff1f3",
        "on-secondary-fixed": "#111c2d",
        "on-primary-fixed": "#002113",
        "primary-fixed": "#6ffbbe",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        base: "4px",
        lg: "24px",
        md: "16px",
        xl: "32px",
        gutter: "24px",
        xs: "4px",
        sm: "8px",
        xxl: "48px",
        "margin-desktop": "64px",
        "margin-mobile": "16px",
        "max-width": "1280px",
      },
      fontFamily: {
        "label-md": ["var(--font-inter)"],
        "display-lg": ["var(--font-inter)"],
        "headline-sm": ["var(--font-inter)"],
        "headline-lg-mobile": ["var(--font-inter)"],
        "headline-lg": ["var(--font-inter)"],
        "body-md": ["var(--font-inter)"],
        "body-lg": ["var(--font-inter)"],
        "body-sm": ["var(--font-inter)"],
        "headline-md": ["var(--font-inter)"],
      },
      fontSize: {
        "label-md": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-sm": ["20px", { lineHeight: "1.4", fontWeight: "600" }],
        "headline-lg-mobile": ["28px", { lineHeight: "1.3", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "1.3", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "1.4", fontWeight: "600" }],
      },
      maxWidth: {
        "max-width": "1280px",
      },
    },
  },
};

export default config;
